

name: Build mediapipe AAR

# Triggers
on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when a version tag is pushed
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching numeric semver tags, i.e., 1.0.0, 20.15.10

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Build mediapipe docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write    
    outputs:
      DOCKER_METADATA_OUTPUT_TAGS: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout code from this repository
        uses: actions/checkout@v4
      - name: Checkout mediapipe
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'google/mediapipe'
          path: 'mediapipe'
      - name: Get the mediapipe commmit hash
        id: get_mp_hash
        run: cd mediapipe && echo "VERSION=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Copy our scripts into mediapipe root
        run: |
          cp image_check.sh mediapipe/
          cp install_android.sh mediapipe/
          cp build_android_example.sh mediapipe/
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./mediapipe
          file: mediapipe/Dockerfile
          push: true
          load: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
          cache-from: type=gha
          cache-to: type=gha,mode=max
  run-on-image:
    name: run things on mediapipe image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write    
    needs: build-image
    steps:
      - name: Checkout code from this repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull image
        env: 
          DOCKER_METADATA_OUTPUT_TAGS: ${{needs.build-image.outputs.DOCKER_METADATA_OUTPUT_TAGS}}
        run: |
          docker pull $DOCKER_METADATA_OUTPUT_TAGS
      - name: Start image container and leave running
        env: 
          DOCKER_METADATA_OUTPUT_TAGS: ${{needs.build-image.outputs.DOCKER_METADATA_OUTPUT_TAGS}}
        run: |
          docker run --name mediapipe $DOCKER_METADATA_OUTPUT_TAGS /bin/bash "echo Started; sleep infinity" &
      - name: Verify mediapipe docker image by building hello world example
        run: |
          docker exec mediapipe bash ./image_check.sh
      - name: install android sdk / ndk in docker
        run: |
          docker exec mediapipe bash ./install_android.sh
      - name: Build an android example
        run: |
          docker exec mediapipe bash ./build_android_example.sh




